"""Generate the built-in translation match tables and checked format macros."""
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]


def literal(value):
    return json.dumps(value, ensure_ascii=False)


def generate():
    catalog = json.loads((ROOT / "src/translations.json").read_text(encoding="utf-8"))
    for russian, english in catalog.items():
        if sorted(re.findall(r"\{[^{}]*\}", russian)) != sorted(re.findall(r"\{[^{}]*\}", english)):
            raise ValueError(f"Different format placeholders: {russian}")
    lines = ["// Generated by scripts/update_i18n.py; edit translations.json instead.",
             "fn translate(language: Language, text: &str) -> &str {", "    match language {",
             "        Language::En => match text {"]
    lines += [f"            {literal(ru)} => {literal(en)}," for ru, en in catalog.items()]
    lines += ["            _ => text,", "        },", "        Language::Ru => match text {"]
    reverse = {en: ru for ru, en in reversed(list(catalog.items()))}
    lines += [f"            {literal(en)} => {literal(ru)}," for en, ru in reverse.items()]
    lines += ["            _ => text,", "        },", "    }", "}", "", "macro_rules! trf {"]
    for ru, en in catalog.items():
        if "{" not in ru:
            continue
        lines += [f"    ({literal(ru)} $($args:tt)*) => {{", "        {",
                  "            if $crate::i18n::current() == $crate::i18n::Language::Ru {",
                  f"                format!({literal(ru)} $($args)*)", "            } else {",
                  f"                format!({literal(en)} $($args)*)", "            }", "        }", "    };"]
    lines += ["}", "pub(crate) use trf;", ""]
    output = "\n".join(lines)
    # rustfmt formats the generated table along with ordinary Rust code. Use
    # the pinned toolchain's formatter so --check verifies its exact result.
    import subprocess
    output = subprocess.run(["rustfmt", "--edition", "2021", "--emit", "stdout"],
                            input=output, text=True, encoding="utf-8", capture_output=True, check=True,
                            cwd=ROOT).stdout
    target = ROOT / "src/i18n_catalog.rs"
    if "--check" in sys.argv:
        if not target.exists() or target.read_text(encoding="utf-8") != output:
            raise ValueError("Translation catalog is stale; run python -B scripts/update_i18n.py")
        print("Verified built-in EN/RU catalog and format placeholders")
    else:
        target.write_text(output, encoding="utf-8")
        print(f"Generated {len(catalog)} built-in EN/RU translations")


if __name__ == "__main__":
    generate()
