// Generated by scripts/update_i18n.py; edit translations.json instead.
fn translate(language: Language, text: &str) -> &str {
    match language {
        Language::En => match text {
            "HTTP-клиент: {e}" => "HTTP client: {e}",
            "некорректный адрес запроса" => "invalid request URL",
            "[пароль скрыт]" => "[password hidden]",
            "[токен скрыт]" => "[token hidden]",
            "[salt скрыт]" => "[salt hidden]",
            "сервер прислал некорректный UTF-8" => "server returned invalid UTF-8",
            "сервер не прислал список альбомов" => "server did not return an album list",
            "сервер прислал некорректный список альбомов" => "server returned an invalid album list",
            "сервер прислал неполную страницу альбомов; полный обход прерван" => "server returned an incomplete album page; full scan stopped",
            "сервер не прислал альбом для проверки библиотеки" => "server did not return an album for the library scan",
            "сервер прислал другой альбом для проверки библиотеки" => "server returned a different album for the library scan",
            "сервер прислал некорректный список песен" => "server returned an invalid song list",
            "сервер прислал неполный список песен альбома" => "server returned an incomplete album song list",
            "обложка: HTTP {} — {}" => "cover: HTTP {} — {}",
            "поток: HTTP {} — {}" => "stream: HTTP {} — {}",
            "слишком много перенаправлений" => "too many redirects",
            "сервер перенаправляет на другой адрес; укажите в настройках итоговый адрес сервера" => "server redirects to another origin; enter the final server URL in settings",
            "некорректный адрес сервера" => "invalid server URL",
            "адрес сервера без хоста" => "server URL has no host",
            "адрес сервера должен быть HTTPS (HTTP допустим только для localhost) и без логина, параметров или фрагмента" => "server URL must use HTTPS (HTTP is allowed only for localhost), without credentials, query or fragment",
            "не удалось прочитать ответ сервера: {e}" => "could not read the server response: {e}",
            "ответ сервера слишком большой" => "server response is too large",
            "сеть: сервер не отвечает; проверьте адрес и соединение" => "network: server is not responding; check its URL and your connection",
            "сеть: {root}" => "network: {root}",
            "не удалось разобрать ответ сервера" => "could not parse the server response",
            "ответ не похож на Subsonic API (нет subsonic-response)" => "response is not a Subsonic API response (missing subsonic-response)",
            "сервер отклонил запрос" => "server rejected the request",
            "сервер: {message} (код {code})" => "server: {message} (code {code})",
            "сервер: {message}" => "server: {message}",
            "не удалось перенести прежний индекс кеша: {error}; аудиофайлы сохранены" => "could not migrate the previous cache index: {error}; audio files were kept",
            "путь трека в индексе кеша небезопасен" => "unsafe track path in the cache index",
            "трек уже находится в кеше" => "track is already cached",
            "трек уже загружается" => "track is already downloading",
            "папка назначения кеша содержит ссылку или небезопасный путь" => "cache destination contains a link or an unsafe path",
            "путь трека выходит за пределы папки кеша" => "track path is outside the cache folder",
            "путь файла содержит ссылку или выходит за пределы кеша" => "file path contains a link or is outside the cache folder",
            "не удалось удалить файл: {err}" => "could not delete the file: {err}",
            "не удалось удалить файлов: {count}" => "could not delete files: {count}",
            "индекс кеша не был прочитан; сохранение заблокировано во избежание потери данных" => "cache index could not be read; saving is blocked to prevent data loss",
            "индекс кеша слишком большой" => "cache index is too large",
            "не удалось создать кеш: {e}" => "could not create the cache: {e}",
            "в индексе кеша пропущено записей с небезопасным путём: {dropped}" => "skipped unsafe entries in the cache index: {dropped}",
            "индекс кеша повреждён и начат заново; старый файл сохранён как {name}" => "cache index was damaged and reset; the old file was saved as {name}",
            "индекс кеша повреждён; копию сделать не удалось, сохранение индекса заблокировано" => "cache index is damaged; backup failed, index saving is blocked",
            "файл индекса слишком большой" => "index file is too large",
            "воспроизведение остановлено" => "playback stopped",
            "декодеру нужно дождаться дополнительных данных" => "decoder needs more data",
            "сервер слишком медленно отдаёт трек" => "server is streaming the track too slowly",
            "не удалось открыть {}: {e}" => "could not open {}: {e}",
            "внутренняя ошибка при загрузке трека" => "internal error while downloading the track",
            "сервер прислал слишком большой файл" => "server returned a file that is too large",
            "не удалось создать {parent:?}: {e}" => "could not create {parent:?}: {e}",
            "не удалось создать {}: {e}" => "could not create {}: {e}",
            "поток оборвался: {e}" => "stream interrupted: {e}",
            "поток превысил допустимый размер файла" => "stream exceeded the file size limit",
            "не удалось записать кеш: {e}" => "could not write the cache: {e}",
            "не удалось сохранить кеш: {e}" => "could not save the cache: {e}",
            "сервер прислал пустой трек" => "server returned an empty track",
            "поток оборвался до конца трека" => "stream ended before the track was complete",
            "путь файла кеша изменился во время загрузки" => "cache file path changed during the download",
            "не удалось завершить файл кеша: {e}" => "could not finish the cache file: {e}",
            "внутренняя ошибка при проверке библиотеки" => "internal error while scanning the library",
            "сервер прислал больше альбомов, чем запрошено в одной странице" => "server returned more albums than requested in a page",
            "список альбомов изменился во время обхода или сервер повторяет страницу; повторите проверку" => "album list changed during the scan or the server repeated a page; try again",
            "слишком много альбомов: полный обход прерван, список не обрезан молча" => "too many albums: full scan stopped without silently truncating the list",
            "метаданные библиотеки превышают 32 МБ; полный обход прерван, прежний список сохранён" => "library metadata exceeds 32 MiB; full scan stopped and the previous list was kept",
            "слишком много песен: полный обход прерван, список не обрезан молча" => "too many songs: full scan stopped without silently truncating the list",
            "слишком много альбомов для постраничного обхода" => "too many albums for a paginated scan",
            "проверка библиотеки отменена" => "library scan cancelled",
            "не удалось прочитать {what}: {err}" => "could not read {what}: {err}",
            "{what} слишком большой; файл сохранён без изменений" => "{what} is too large; the file was kept unchanged",
            "не удалось прочитать {what}: {e}" => "could not read {what}: {e}",
            "список известных песен" => "known-song list",
            "список известных песен повреждён; файл сохранён без изменений" => "known-song list is damaged; the file was kept unchanged",
            "неподдерживаемый список известных песен; файл сохранён без изменений" => "unsupported known-song list; the file was kept unchanged",
            "список песен сервера" => "server song list",
            "список песен сервера повреждён" => "server song list is damaged",
            "неподдерживаемый список песен сервера" => "unsupported server song list",
            "не удалось сохранить список песен сервера: {e}" => "could not save the server song list: {e}",
            "список песен сервера слишком большой; прежний файл не заменён" => "server song list is too large; the previous file was kept",
            "не удалось определить папку списка песен сервера" => "could not locate the server song list folder",
            "не удалось создать папку списка песен сервера: {e}" => "could not create the server song list folder: {e}",
            "{problem}; резервная копия недоступна, прежний файл оставлен на месте" => "{problem}; backup unavailable, the previous file was kept",
            "{problem}; старая копия сохранена рядом" => "{problem}; the old copy was saved alongside",
            "{problem}; не удалось сохранить копию: {error}; прежний файл оставлен на месте" => "{problem}; backup failed: {error}; the previous file was kept",
            "не удалось сохранить список песен: {e}" => "could not save the song list: {e}",
            "список известных песен слишком большой; прежний файл не заменён" => "known-song list is too large; the previous file was kept",
            "не удалось определить папку списка песен" => "could not locate the song list folder",
            "не удалось создать папку списка песен: {e}" => "could not create the song list folder: {e}",
            "не удалось открыть {path:?}: {err}" => "could not open {path:?}: {err}",
            "файл {path:?} превышает лимит {} МБ" => "file {path:?} exceeds the {} MiB limit",
            "не удалось прочитать {path:?}: {e}" => "could not read {path:?}: {e}",
            "файл {path:?} не в UTF-8" => "file {path:?} is not UTF-8",
            "не удалось записать {path:?}: {e}" => "could not write {path:?}: {e}",
            "на этой платформе пароль нельзя сохранить безопасно" => "the password cannot be saved securely on this platform",
            "неизвестный формат пароля" => "unknown password format",
            "повреждённый пароль" => "damaged password",
            "пароль сохранён для Windows и не может быть прочитан на этой системе" => "password was saved for Windows and cannot be read on this system",
            "пароль слишком длинный" => "password is too long",
            "защита пароля Windows: {}" => "Windows password protection: {}",
            "повреждённый ответ Windows DPAPI" => "invalid Windows DPAPI response",
            "оригинал" => "original",
            "mp3 (транскод)" => "mp3 (transcoded)",
            "config.json повреждён — загружены значения по умолчанию; старый файл сохранён как {name}" => "config.json is damaged — defaults were loaded; the old file was saved as {name}",
            "config.json повреждён; резервная копия не создана, сохранение заблокировано" => "config.json is damaged; backup failed and saving is blocked",
            "{err}; сохранение заблокировано" => "{err}; saving is blocked",
            "пароль сервера не удалось расшифровать; введите его заново в настройках" => "could not decrypt the server password; enter it again in settings",
            "не удалось защитить сохранённый пароль: {err}" => "could not protect the saved password: {err}",
            "config.json не был прочитан; сохранение заблокировано во избежание потери данных" => "config.json could not be read; saving is blocked to prevent data loss",
            "не удалось создать {dir:?}: {e}" => "could not create {dir:?}: {e}",
            "пароль не сохранён: {err}" => "password was not saved: {err}",
            "не удалось защитить пароль; настройки не изменены: {err}" => "could not protect the password; settings were kept unchanged: {err}",
            "config.json слишком большой" => "config.json is too large",
            "НОВЫЕ АЛЬБОМЫ" => "NEW ALBUMS",
            "сначала укажите сервер, логин и пароль в настройках" => "enter a server URL, username and password in settings first",
            "не удалось создать {}: {err}" => "could not create {}: {err}",
            "СЛУЧАЙНЫЕ ЛОКАЛЬНЫЕ АЛЬБОМЫ" => "RANDOM LOCAL ALBUMS",
            "ЛОКАЛЬНЫЕ АЛЬБОМЫ" => "LOCAL ALBUMS",
            "альбом не найден — обновите список на диске" => "album not found — refresh the files on disk",
            "заполните адрес, логин и пароль" => "enter a URL, username and password",
            "дождитесь окончания загрузок перед сменой сервера, формата или папки кеша" => "wait for downloads to finish before changing the server, format or cache folder",
            "загружаю библиотеку Navidrome…" => "loading the Navidrome library…",
            "проверяю библиотеку Navidrome…" => "scanning the Navidrome library…",
            "библиотека обновлена: {count} треков с сервера" => "library refreshed: {count} songs from the server",
            "не удалось обновить библиотеку после {albums} альбомов: {err}" => "could not refresh the library after {albums} albums: {err}",
            "проверка библиотеки неожиданно прервалась" => "library scan ended unexpectedly",
            "запомнено альбомов: {}; новые песни будут скачиваться автоматически" => "remembered albums: {}; new songs will be cached automatically",
            "проверено альбомов: {}; добавлено в загрузки: {}" => "albums checked: {}; downloads added: {}",
            "проверка библиотеки остановлена после {} альбомов (добавлено: {}): {err}" => "library scan stopped after {} albums (added: {}): {err}",
            "скачано: {} — {}" => "downloaded: {} — {}",
            "не скачалось: {err}" => "download failed: {err}",
            "файл уже лежит в папке кеша: {}" => "file is already in the cache folder: {}",
            "уже в кеше: {}" => "already cached: {}",
            "добавлено в загрузки" => "added to downloads",
            "в загрузки добавлено треков: {added}" => "tracks added to downloads: {added}",
            "все треки уже скачаны" => "all tracks are already downloaded",
            "аудиовыход недоступен" => "audio output unavailable",
            "файл кеша недоступен — обновите список" => "cache file unavailable — refresh the list",
            "трек не скачан; настройте подключение к серверу" => "track is not cached; configure a server connection",
            "не удалось загрузить трек для воспроизведения" => "could not download the track for playback",
            "перемотка станет доступна, когда трек докачается" => "seeking will become available as the track downloads",
            "аудиоустройство недоступно" => "audio device unavailable",
            "аудиоустройство было недоступно" => "audio device was unavailable",
            "библиотека пуста — добавьте музыку или обновите список" => "library is empty — add music or refresh the list",
            "поток аудиоустройства прерван" => "audio device stream interrupted",
            "аудиоустройство появилось" => "audio device appeared",
            "аудиоустройство изменилось" => "audio device changed",
            "аудиоустройство исчезло" => "audio device disappeared",
            "BEAT // NAVIDROME КЛИЕНТ" => "BEAT // NAVIDROME CLIENT",
            "музыка, кеш и плеер в одном окне" => "music, cache and playback in one window",
            "[ НАСТРОЙКИ ]" => "[ SETTINGS ]",
            "КЕШ {cached} · {}" => "CACHE {cached} · {}",
            "СЕРВЕР…" => "SERVER…",
            "СЕРВЕР ГОТОВ" => "SERVER READY",
            "НЕТ СВЯЗИ" => "OFFLINE",
            "БИБЛИОТЕКА" => "LIBRARY",
            "поиск" => "search",
            "новые альбомы" => "new albums",
            "случайные альбомы" => "random albums",
            "СЛУЧАЙНЫЕ АЛЬБОМЫ" => "RANDOM ALBUMS",
            "все артисты" => "all artists",
            "библиотека" => "library",
            "часто прослушиваемые" => "most played",
            "ЗАГРУЗКИ" => "DOWNLOADS",
            "↓ скачать все песни" => "↓ download all songs",
            "Найти все треки Navidrome и поставить отсутствующие в очередь" => "Find all Navidrome tracks and queue missing downloads",
            "запоминаю библиотеку" => "remembering the library",
            "проверяю библиотеку" => "scanning the library",
            "{label}: {} альбомов" => "{label}: {} albums",
            "новых загрузок: {}" => "new downloads: {}",
            "× остановить поиск" => "× stop scan",
            "Уже запущенные и добавленные в очередь загрузки продолжатся" => "Running and queued downloads will continue",
            "поиск остановлен; уже добавленные загрузки продолжаются" => "scan stopped; downloads already queued will continue",
            "нет активных загрузок" => "no active downloads",
            "в очереди" => "queued",
            "× очистить очередь" => "× clear download queue",
            "Отменить ожидающие загрузки; уже начатые продолжатся" => "Cancel waiting downloads; running downloads will continue",
            "поиск и ожидающие загрузки отменены; начатые продолжаются" => "scan and waiting downloads cancelled; running downloads will continue",
            "КЕШ" => "CACHE",
            "треков" => "tracks",
            "в кеше" => "cached",
            "локальных" => "local",
            "размер" => "size",
            "открыть папку кеша" => "open cache folder",
            "× точно очистить кеш?" => "× confirm cache cleanup?",
            "× очистить кеш" => "× clear cache",
            "кеш очищен" => "cache cleared",
            "ничего не играет" => "nothing is playing",
            "предыдущий" => "previous",
            "следующий" => "next",
            "стоп" => "stop",
            "случайный порядок" => "shuffle",
            "повтор выключен — нажмите: весь список" => "repeat off — click: all tracks",
            "повтор всего списка — нажмите: одна песня" => "repeat all — click: one track",
            "повтор одной песни — нажмите: выключить" => "repeat one — click: off",
            "громкость" => "volume",
            "● ОЖИДАНИЕ ЗАГРУЗКИ" => "● WAITING FOR DOWNLOAD",
            "● БУФЕРИЗАЦИЯ" => "● BUFFERING",
            "● ИГРАЕТ" => "● PLAYING",
            "● ГОТОВО" => "● READY",
            "треков в очереди: {}" => "queue: {} tracks",
            "кеш: {}" => "cache: {}",
            "конфиг не сохранён: {err}" => "config was not saved: {err}",
            "загрузка…" => "loading…",
            "АРТИСТЫ" => "ARTISTS",
            "артистов пока нет — добавьте файлы в папку кеша или настройте сервер" => "no artists yet — add music folders or configure a server",
            "‹ назад" => "‹ back",
            "альбомов: {}" => "albums: {}",
            "СЕРВЕР НЕ НАСТРОЕН" => "SERVER NOT CONFIGURED",
            "укажите адрес Navidrome, логин и пароль — или закиньте файлы прямо в папку кеша" => "enter a Navidrome URL, username and password — or add local music folders",
            "[ БИБЛИОТЕКА ]" => "[ LIBRARY ]",
            "[ ОТКРЫТЬ ПАПКУ КЕША ]" => "[ OPEN CACHE FOLDER ]",
            "треков: {}, {}" => "tracks: {}, {}",
            "[ СЛУШАТЬ ]" => "[ PLAY ]",
            "[ СКАЧАТЬ АЛЬБОМ ]" => "[ DOWNLOAD ALBUM ]",
            "качается" => "downloading",
            "на диске" => "on disk",
            "скачать в кеш" => "download to cache",
            "этот альбом уже лежит в папке кеша" => "this album is already in the cache folder",
            "[ ПОИСК ]" => "[ SEARCH ]",
            "артист, альбом или трек…" => "artist, album or track…",
            "найти" => "find",
            "ищу…" => "searching…",
            "введите запрос" => "enter a search query",
            "ничего не найдено" => "nothing found",
            "АЛЬБОМЫ" => "ALBUMS",
            "ТРЕКИ" => "TRACKS",
            "ЛОКАЛЬНЫЕ ФАЙЛЫ" => "LOCAL FILES",
            "НА ДИСКЕ" => "ON DISK",
            "обновить" => "refresh",
            "обновляю…" => "refreshing…",
            "всего {total} · на диске {disk}" => "total {total} · on disk {disk}",
            "открыть папку" => "open folder",
            "загружаю с сервера: {} альбомов" => "loading from server: {} albums",
            "× остановить" => "× stop",
            "Список останется прежним" => "The previous list will be kept",
            "фильтр: название, артист или альбом…" => "filter: title, artist or album…",
            "сбросить фильтр" => "clear filter",
            "найдено {found} из {total}" => "found {found} of {total}",
            "ищу файлы…" => "scanning files…",
            "[ ОТКРЫТЬ ПАПКУ ]" => "[ OPEN FOLDER ]",
            "БИБЛИОТЕКА ПУСТА" => "LIBRARY IS EMPTY",
            "нажмите «обновить», чтобы загрузить список с сервера" => "click “refresh” to load the server song list",
            "НИЧЕГО НЕ НАЙДЕНО" => "NOTHING FOUND",
            "измените фильтр или сбросьте его" => "change or clear the filter",
            "удалить из кеша" => "delete from cache",
            "слушать" => "play",
            "удалено из кеша" => "deleted from cache",
            "[ ЧАСТО ПРОСЛУШИВАЕМЫЕ ]" => "[ MOST PLAYED ]",
            "сканирую папку…" => "scanning folders…",
            "{} треков по истории BEAT" => "{} tracks from your BEAT history",
            "закиньте файлы в папку кеша или скачайте треки с сервера" => "add music folders or download tracks from the server",
            "ПОКА НЕТ ИСТОРИИ ПРОСЛУШИВАНИЙ" => "NO LISTENING HISTORY YET",
            "включите что-нибудь — треки появятся здесь по числу прослушиваний" => "play something — tracks will appear here by play count",
            "> адрес Navidrome (https://…)" => "> Navidrome URL (https://…)",
            "> логин" => "> username",
            "> пароль" => "> password",
            "[ скрыть ]" => "[ hide ]",
            "[ показать ]" => "[ show ]",
            "> папка кеша" => "> cache folder",
            "по умолчанию: {}" => "default: {}",
            "[ выбрать ]" => "[ choose ]",
            "[ сбросить ]" => "[ reset ]",
            "> музыкальные папки" => "> music folders",
            "Убрать папку из библиотеки" => "Remove folder from the library",
            "[ ДОБАВИТЬ ПАПКУ ]" => "[ ADD FOLDER ]",
            "Эти папки читаются напрямую; очистка кеша их не затрагивает." => "These folders are read directly; clearing the cache does not affect them.",
            "> формат загрузки" => "> download format",
            "mp3 (транскод сервером)" => "mp3 (transcoded by server)",
            "битрейт, kbps" => "bitrate, kbps",
            "параллельных загрузок" => "parallel downloads",
            "автоматически кешировать новые песни" => "automatically cache new songs",
            "При первом включении запоминает текущие треки; затем проверяет сервер каждые 10 минут, пока BEAT открыт." => "First remembers existing tracks, then checks the server every 10 minutes while BEAT is open.",
            "[ ПРОВЕРИТЬ СВЯЗЬ ]" => "[ TEST CONNECTION ]",
            "проверяю…" => "checking…",
            "связь есть" => "connected",
            "[ СОХРАНИТЬ ]" => "[ SAVE ]",
            "[ ОТМЕНА ]" => "[ CANCEL ]",
            "[ ОЧЕРЕДЬ ]" => "[ QUEUE ]",
            "[ ОСТАВИТЬ ТЕКУЩИЙ ТРЕК ]" => "[ KEEP CURRENT TRACK ]",
            "Очередь пуста" => "Queue is empty",
            "Убрать из очереди" => "Remove from queue",
            "день" => "light",
            "ночь" => "dark",
            "Светлая тема" => "Light theme",
            "Тёмная тема" => "Dark theme",
            "Свернуть" => "Minimize",
            "Развернуть / восстановить" => "Maximize / restore",
            "Закрыть" => "Close",
            "скачать альбом" => "download album",
            "пауза" => "pause",
            "продолжить" => "resume",
            "начать воспроизведение" => "start playback",
            "локальный файл — лежит в папке кеша, не скачан с сервера" => "local file — read directly from a music folder",
            "без альбома" => "no album",
            "неизвестный артист" => "unknown artist",
            "раз" => "plays",
            "раза" => "plays",
            "{kb:.0} КБ" => "{kb:.0} KiB",
            "{:.1} МБ" => "{:.1} MiB",
            "{:.2} ГБ" => "{:.2} GiB",
            "не удалось создать мьютекс: {}" => "could not create the mutex: {}",
            "BEAT уже запущен" => "BEAT is already running",
            "{err}.\n\nЗакройте уже открытое окно BEAT и запустите это снова." => "{err}.\n\nClose the other BEAT window and launch this one again.",
            "BEAT — внутренняя ошибка" => "BEAT — internal error",
            "BEAT не смог продолжить работу.\n\n{info}" => "BEAT could not continue.\n\n{info}",
            "BEAT — не удалось открыть окно" => "BEAT — could not open the window",
            "слишком большие или повреждённые метаданные аудио" => "audio metadata is oversized or damaged",
            "контейнер не содержит поддерживаемый Opus-трек" => "container has no supported Opus audio track",
            "Opus без временной шкалы" => "Opus has no time base",
            "частота Opus" => "Opus sample rate",
            "Opus: поддерживаются моно и стерео" => "Opus: only mono and stereo are supported",
            "каналы Opus" => "Opus channels",
            "Opus: слишком много повреждённых пакетов" => "Opus: too many damaged packets",
            "Opus: слишком большая дистанция точной перемотки" => "Opus: accurate seek distance is too large",
            "Opus: повреждённый поток" => "Opus: damaged stream",
            "аудиовыход недоступен: {e}" => "audio output unavailable: {e}",
            "некорректная позиция перемотки" => "invalid seek position",
            "перемотка недоступна: {e}" => "seeking unavailable: {e}",
            "не найдено подходящее устройство вывода" => "no suitable audio output device found",
            "beat: аудиопоток: {err}" => "beat: audio stream: {err}",
            "не удалось прочитать {}: {e}" => "could not read {}: {e}",
            "метаданные: {e}" => "metadata: {e}",
            "декодер: {e}" => "decoder: {e}",
            "декодер не смог прочитать повреждённый файл" => "decoder could not read the damaged file",
            "сохранение заблокировано, прежний файл оставлен на месте" => "saving is blocked; the previous file was kept",
            "прежний файл сохранён отдельно" => "the previous file was saved separately",
            "не удалось прочитать сессию: {detail}" => "could not read the session: {detail}",
            "прежняя сессия недоступна; её файл не заменён" => "previous session unavailable; its file was kept",
            "не удалось сохранить сессию: {e}" => "could not save the session: {e}",
            "сессия слишком большая; прежний файл не заменён" => "session is too large; the previous file was kept",
            "не удалось определить папку сессии" => "could not locate the session folder",
            "не удалось создать папку сессии: {e}" => "could not create the session folder: {e}",
            "история прослушиваний повреждена; прежний файл сохранён рядом" => "listening history is damaged; the previous file was saved alongside",
            "историю прослушиваний не удалось прочитать; её сохранение заблокировано" => "listening history could not be read; saving is blocked",
            "история прослушиваний не прочитана; прежний файл не будет перезаписан" => "listening history could not be read; the previous file will not be overwritten",
            "история прослушиваний слишком большая; прежний файл не заменён" => "listening history is too large; the previous file was kept",
            "ЛОКАЛЬНО" => "LOCAL MODE",
            "Windows media controls: {error}" => "Windows media controls: {error}",
            "файл не найден в папках музыки — обновите список" => "File missing from the music folders — refresh the library",
            "Добавьте папку с MP3 / FLAC / OGG / Opus / WAV / M4A в настройках" => "Add a folder with MP3 / FLAC / OGG / Opus / WAV / M4A files in Settings",
            "МУЗЫКА НЕ НАЙДЕНА" => "NO MUSIC FOUND",
            "Причина: {e}\n\nДля запуска нужен OpenGL 2.1+. Включите 3D-ускорение в настройках ВМ либо запустите программу на обычном рабочем столе." => "Reason: {e}\n\nOpenGL 2.1+ is required. Enable 3D acceleration in the VM settings or run BEAT on a normal desktop.",
            _ => text,
        },
        Language::Ru => match text {
            "Reason: {e}\n\nOpenGL 2.1+ is required. Enable 3D acceleration in the VM settings or run BEAT on a normal desktop." => "Причина: {e}\n\nДля запуска нужен OpenGL 2.1+. Включите 3D-ускорение в настройках ВМ либо запустите программу на обычном рабочем столе.",
            "NO MUSIC FOUND" => "МУЗЫКА НЕ НАЙДЕНА",
            "Add a folder with MP3 / FLAC / OGG / Opus / WAV / M4A files in Settings" => "Добавьте папку с MP3 / FLAC / OGG / Opus / WAV / M4A в настройках",
            "File missing from the music folders — refresh the library" => "файл не найден в папках музыки — обновите список",
            "Windows media controls: {error}" => "Windows media controls: {error}",
            "LOCAL MODE" => "ЛОКАЛЬНО",
            "listening history is too large; the previous file was kept" => "история прослушиваний слишком большая; прежний файл не заменён",
            "listening history could not be read; the previous file will not be overwritten" => "история прослушиваний не прочитана; прежний файл не будет перезаписан",
            "listening history could not be read; saving is blocked" => "историю прослушиваний не удалось прочитать; её сохранение заблокировано",
            "listening history is damaged; the previous file was saved alongside" => "история прослушиваний повреждена; прежний файл сохранён рядом",
            "could not create the session folder: {e}" => "не удалось создать папку сессии: {e}",
            "could not locate the session folder" => "не удалось определить папку сессии",
            "session is too large; the previous file was kept" => "сессия слишком большая; прежний файл не заменён",
            "could not save the session: {e}" => "не удалось сохранить сессию: {e}",
            "previous session unavailable; its file was kept" => "прежняя сессия недоступна; её файл не заменён",
            "could not read the session: {detail}" => "не удалось прочитать сессию: {detail}",
            "the previous file was saved separately" => "прежний файл сохранён отдельно",
            "saving is blocked; the previous file was kept" => "сохранение заблокировано, прежний файл оставлен на месте",
            "decoder could not read the damaged file" => "декодер не смог прочитать повреждённый файл",
            "decoder: {e}" => "декодер: {e}",
            "metadata: {e}" => "метаданные: {e}",
            "could not read {}: {e}" => "не удалось прочитать {}: {e}",
            "beat: audio stream: {err}" => "beat: аудиопоток: {err}",
            "no suitable audio output device found" => "не найдено подходящее устройство вывода",
            "seeking unavailable: {e}" => "перемотка недоступна: {e}",
            "invalid seek position" => "некорректная позиция перемотки",
            "audio output unavailable: {e}" => "аудиовыход недоступен: {e}",
            "Opus: damaged stream" => "Opus: повреждённый поток",
            "Opus: accurate seek distance is too large" => "Opus: слишком большая дистанция точной перемотки",
            "Opus: too many damaged packets" => "Opus: слишком много повреждённых пакетов",
            "Opus channels" => "каналы Opus",
            "Opus: only mono and stereo are supported" => "Opus: поддерживаются моно и стерео",
            "Opus sample rate" => "частота Opus",
            "Opus has no time base" => "Opus без временной шкалы",
            "container has no supported Opus audio track" => "контейнер не содержит поддерживаемый Opus-трек",
            "audio metadata is oversized or damaged" => "слишком большие или повреждённые метаданные аудио",
            "BEAT — could not open the window" => "BEAT — не удалось открыть окно",
            "BEAT could not continue.\n\n{info}" => "BEAT не смог продолжить работу.\n\n{info}",
            "BEAT — internal error" => "BEAT — внутренняя ошибка",
            "{err}.\n\nClose the other BEAT window and launch this one again." => "{err}.\n\nЗакройте уже открытое окно BEAT и запустите это снова.",
            "BEAT is already running" => "BEAT уже запущен",
            "could not create the mutex: {}" => "не удалось создать мьютекс: {}",
            "{:.2} GiB" => "{:.2} ГБ",
            "{:.1} MiB" => "{:.1} МБ",
            "{kb:.0} KiB" => "{kb:.0} КБ",
            "plays" => "раз",
            "unknown artist" => "неизвестный артист",
            "no album" => "без альбома",
            "local file — read directly from a music folder" => "локальный файл — лежит в папке кеша, не скачан с сервера",
            "start playback" => "начать воспроизведение",
            "resume" => "продолжить",
            "pause" => "пауза",
            "download album" => "скачать альбом",
            "Close" => "Закрыть",
            "Maximize / restore" => "Развернуть / восстановить",
            "Minimize" => "Свернуть",
            "Dark theme" => "Тёмная тема",
            "Light theme" => "Светлая тема",
            "dark" => "ночь",
            "light" => "день",
            "Remove from queue" => "Убрать из очереди",
            "Queue is empty" => "Очередь пуста",
            "[ KEEP CURRENT TRACK ]" => "[ ОСТАВИТЬ ТЕКУЩИЙ ТРЕК ]",
            "[ QUEUE ]" => "[ ОЧЕРЕДЬ ]",
            "[ CANCEL ]" => "[ ОТМЕНА ]",
            "[ SAVE ]" => "[ СОХРАНИТЬ ]",
            "connected" => "связь есть",
            "checking…" => "проверяю…",
            "[ TEST CONNECTION ]" => "[ ПРОВЕРИТЬ СВЯЗЬ ]",
            "First remembers existing tracks, then checks the server every 10 minutes while BEAT is open." => "При первом включении запоминает текущие треки; затем проверяет сервер каждые 10 минут, пока BEAT открыт.",
            "automatically cache new songs" => "автоматически кешировать новые песни",
            "parallel downloads" => "параллельных загрузок",
            "bitrate, kbps" => "битрейт, kbps",
            "mp3 (transcoded by server)" => "mp3 (транскод сервером)",
            "> download format" => "> формат загрузки",
            "These folders are read directly; clearing the cache does not affect them." => "Эти папки читаются напрямую; очистка кеша их не затрагивает.",
            "[ ADD FOLDER ]" => "[ ДОБАВИТЬ ПАПКУ ]",
            "Remove folder from the library" => "Убрать папку из библиотеки",
            "> music folders" => "> музыкальные папки",
            "[ reset ]" => "[ сбросить ]",
            "[ choose ]" => "[ выбрать ]",
            "default: {}" => "по умолчанию: {}",
            "> cache folder" => "> папка кеша",
            "[ show ]" => "[ показать ]",
            "[ hide ]" => "[ скрыть ]",
            "> password" => "> пароль",
            "> username" => "> логин",
            "> Navidrome URL (https://…)" => "> адрес Navidrome (https://…)",
            "play something — tracks will appear here by play count" => "включите что-нибудь — треки появятся здесь по числу прослушиваний",
            "NO LISTENING HISTORY YET" => "ПОКА НЕТ ИСТОРИИ ПРОСЛУШИВАНИЙ",
            "add music folders or download tracks from the server" => "закиньте файлы в папку кеша или скачайте треки с сервера",
            "{} tracks from your BEAT history" => "{} треков по истории BEAT",
            "scanning folders…" => "сканирую папку…",
            "[ MOST PLAYED ]" => "[ ЧАСТО ПРОСЛУШИВАЕМЫЕ ]",
            "deleted from cache" => "удалено из кеша",
            "play" => "слушать",
            "delete from cache" => "удалить из кеша",
            "change or clear the filter" => "измените фильтр или сбросьте его",
            "NOTHING FOUND" => "НИЧЕГО НЕ НАЙДЕНО",
            "click “refresh” to load the server song list" => "нажмите «обновить», чтобы загрузить список с сервера",
            "LIBRARY IS EMPTY" => "БИБЛИОТЕКА ПУСТА",
            "[ OPEN FOLDER ]" => "[ ОТКРЫТЬ ПАПКУ ]",
            "scanning files…" => "ищу файлы…",
            "found {found} of {total}" => "найдено {found} из {total}",
            "clear filter" => "сбросить фильтр",
            "filter: title, artist or album…" => "фильтр: название, артист или альбом…",
            "The previous list will be kept" => "Список останется прежним",
            "× stop" => "× остановить",
            "loading from server: {} albums" => "загружаю с сервера: {} альбомов",
            "open folder" => "открыть папку",
            "total {total} · on disk {disk}" => "всего {total} · на диске {disk}",
            "refreshing…" => "обновляю…",
            "refresh" => "обновить",
            "ON DISK" => "НА ДИСКЕ",
            "LOCAL FILES" => "ЛОКАЛЬНЫЕ ФАЙЛЫ",
            "TRACKS" => "ТРЕКИ",
            "ALBUMS" => "АЛЬБОМЫ",
            "nothing found" => "ничего не найдено",
            "enter a search query" => "введите запрос",
            "searching…" => "ищу…",
            "find" => "найти",
            "artist, album or track…" => "артист, альбом или трек…",
            "[ SEARCH ]" => "[ ПОИСК ]",
            "this album is already in the cache folder" => "этот альбом уже лежит в папке кеша",
            "download to cache" => "скачать в кеш",
            "on disk" => "на диске",
            "downloading" => "качается",
            "[ DOWNLOAD ALBUM ]" => "[ СКАЧАТЬ АЛЬБОМ ]",
            "[ PLAY ]" => "[ СЛУШАТЬ ]",
            "tracks: {}, {}" => "треков: {}, {}",
            "[ OPEN CACHE FOLDER ]" => "[ ОТКРЫТЬ ПАПКУ КЕША ]",
            "[ LIBRARY ]" => "[ БИБЛИОТЕКА ]",
            "enter a Navidrome URL, username and password — or add local music folders" => "укажите адрес Navidrome, логин и пароль — или закиньте файлы прямо в папку кеша",
            "SERVER NOT CONFIGURED" => "СЕРВЕР НЕ НАСТРОЕН",
            "albums: {}" => "альбомов: {}",
            "‹ back" => "‹ назад",
            "no artists yet — add music folders or configure a server" => "артистов пока нет — добавьте файлы в папку кеша или настройте сервер",
            "ARTISTS" => "АРТИСТЫ",
            "loading…" => "загрузка…",
            "config was not saved: {err}" => "конфиг не сохранён: {err}",
            "cache: {}" => "кеш: {}",
            "queue: {} tracks" => "треков в очереди: {}",
            "● READY" => "● ГОТОВО",
            "● PLAYING" => "● ИГРАЕТ",
            "● BUFFERING" => "● БУФЕРИЗАЦИЯ",
            "● WAITING FOR DOWNLOAD" => "● ОЖИДАНИЕ ЗАГРУЗКИ",
            "volume" => "громкость",
            "repeat one — click: off" => "повтор одной песни — нажмите: выключить",
            "repeat all — click: one track" => "повтор всего списка — нажмите: одна песня",
            "repeat off — click: all tracks" => "повтор выключен — нажмите: весь список",
            "shuffle" => "случайный порядок",
            "stop" => "стоп",
            "next" => "следующий",
            "previous" => "предыдущий",
            "nothing is playing" => "ничего не играет",
            "cache cleared" => "кеш очищен",
            "× clear cache" => "× очистить кеш",
            "× confirm cache cleanup?" => "× точно очистить кеш?",
            "open cache folder" => "открыть папку кеша",
            "size" => "размер",
            "local" => "локальных",
            "cached" => "в кеше",
            "tracks" => "треков",
            "CACHE" => "КЕШ",
            "scan and waiting downloads cancelled; running downloads will continue" => "поиск и ожидающие загрузки отменены; начатые продолжаются",
            "Cancel waiting downloads; running downloads will continue" => "Отменить ожидающие загрузки; уже начатые продолжатся",
            "× clear download queue" => "× очистить очередь",
            "queued" => "в очереди",
            "no active downloads" => "нет активных загрузок",
            "scan stopped; downloads already queued will continue" => "поиск остановлен; уже добавленные загрузки продолжаются",
            "Running and queued downloads will continue" => "Уже запущенные и добавленные в очередь загрузки продолжатся",
            "× stop scan" => "× остановить поиск",
            "new downloads: {}" => "новых загрузок: {}",
            "{label}: {} albums" => "{label}: {} альбомов",
            "scanning the library" => "проверяю библиотеку",
            "remembering the library" => "запоминаю библиотеку",
            "Find all Navidrome tracks and queue missing downloads" => "Найти все треки Navidrome и поставить отсутствующие в очередь",
            "↓ download all songs" => "↓ скачать все песни",
            "DOWNLOADS" => "ЗАГРУЗКИ",
            "most played" => "часто прослушиваемые",
            "library" => "библиотека",
            "all artists" => "все артисты",
            "RANDOM ALBUMS" => "СЛУЧАЙНЫЕ АЛЬБОМЫ",
            "random albums" => "случайные альбомы",
            "new albums" => "новые альбомы",
            "search" => "поиск",
            "LIBRARY" => "БИБЛИОТЕКА",
            "OFFLINE" => "НЕТ СВЯЗИ",
            "SERVER READY" => "СЕРВЕР ГОТОВ",
            "SERVER…" => "СЕРВЕР…",
            "CACHE {cached} · {}" => "КЕШ {cached} · {}",
            "[ SETTINGS ]" => "[ НАСТРОЙКИ ]",
            "music, cache and playback in one window" => "музыка, кеш и плеер в одном окне",
            "BEAT // NAVIDROME CLIENT" => "BEAT // NAVIDROME КЛИЕНТ",
            "audio device disappeared" => "аудиоустройство исчезло",
            "audio device changed" => "аудиоустройство изменилось",
            "audio device appeared" => "аудиоустройство появилось",
            "audio device stream interrupted" => "поток аудиоустройства прерван",
            "library is empty — add music or refresh the list" => "библиотека пуста — добавьте музыку или обновите список",
            "audio device was unavailable" => "аудиоустройство было недоступно",
            "audio device unavailable" => "аудиоустройство недоступно",
            "seeking will become available as the track downloads" => "перемотка станет доступна, когда трек докачается",
            "could not download the track for playback" => "не удалось загрузить трек для воспроизведения",
            "track is not cached; configure a server connection" => "трек не скачан; настройте подключение к серверу",
            "cache file unavailable — refresh the list" => "файл кеша недоступен — обновите список",
            "audio output unavailable" => "аудиовыход недоступен",
            "all tracks are already downloaded" => "все треки уже скачаны",
            "tracks added to downloads: {added}" => "в загрузки добавлено треков: {added}",
            "added to downloads" => "добавлено в загрузки",
            "already cached: {}" => "уже в кеше: {}",
            "file is already in the cache folder: {}" => "файл уже лежит в папке кеша: {}",
            "download failed: {err}" => "не скачалось: {err}",
            "downloaded: {} — {}" => "скачано: {} — {}",
            "library scan stopped after {} albums (added: {}): {err}" => "проверка библиотеки остановлена после {} альбомов (добавлено: {}): {err}",
            "albums checked: {}; downloads added: {}" => "проверено альбомов: {}; добавлено в загрузки: {}",
            "remembered albums: {}; new songs will be cached automatically" => "запомнено альбомов: {}; новые песни будут скачиваться автоматически",
            "library scan ended unexpectedly" => "проверка библиотеки неожиданно прервалась",
            "could not refresh the library after {albums} albums: {err}" => "не удалось обновить библиотеку после {albums} альбомов: {err}",
            "library refreshed: {count} songs from the server" => "библиотека обновлена: {count} треков с сервера",
            "scanning the Navidrome library…" => "проверяю библиотеку Navidrome…",
            "loading the Navidrome library…" => "загружаю библиотеку Navidrome…",
            "wait for downloads to finish before changing the server, format or cache folder" => "дождитесь окончания загрузок перед сменой сервера, формата или папки кеша",
            "enter a URL, username and password" => "заполните адрес, логин и пароль",
            "album not found — refresh the files on disk" => "альбом не найден — обновите список на диске",
            "LOCAL ALBUMS" => "ЛОКАЛЬНЫЕ АЛЬБОМЫ",
            "RANDOM LOCAL ALBUMS" => "СЛУЧАЙНЫЕ ЛОКАЛЬНЫЕ АЛЬБОМЫ",
            "could not create {}: {err}" => "не удалось создать {}: {err}",
            "enter a server URL, username and password in settings first" => "сначала укажите сервер, логин и пароль в настройках",
            "NEW ALBUMS" => "НОВЫЕ АЛЬБОМЫ",
            "config.json is too large" => "config.json слишком большой",
            "could not protect the password; settings were kept unchanged: {err}" => "не удалось защитить пароль; настройки не изменены: {err}",
            "password was not saved: {err}" => "пароль не сохранён: {err}",
            "could not create {dir:?}: {e}" => "не удалось создать {dir:?}: {e}",
            "config.json could not be read; saving is blocked to prevent data loss" => "config.json не был прочитан; сохранение заблокировано во избежание потери данных",
            "could not protect the saved password: {err}" => "не удалось защитить сохранённый пароль: {err}",
            "could not decrypt the server password; enter it again in settings" => "пароль сервера не удалось расшифровать; введите его заново в настройках",
            "{err}; saving is blocked" => "{err}; сохранение заблокировано",
            "config.json is damaged; backup failed and saving is blocked" => "config.json повреждён; резервная копия не создана, сохранение заблокировано",
            "config.json is damaged — defaults were loaded; the old file was saved as {name}" => "config.json повреждён — загружены значения по умолчанию; старый файл сохранён как {name}",
            "mp3 (transcoded)" => "mp3 (транскод)",
            "original" => "оригинал",
            "invalid Windows DPAPI response" => "повреждённый ответ Windows DPAPI",
            "Windows password protection: {}" => "защита пароля Windows: {}",
            "password is too long" => "пароль слишком длинный",
            "password was saved for Windows and cannot be read on this system" => "пароль сохранён для Windows и не может быть прочитан на этой системе",
            "damaged password" => "повреждённый пароль",
            "unknown password format" => "неизвестный формат пароля",
            "the password cannot be saved securely on this platform" => "на этой платформе пароль нельзя сохранить безопасно",
            "could not write {path:?}: {e}" => "не удалось записать {path:?}: {e}",
            "file {path:?} is not UTF-8" => "файл {path:?} не в UTF-8",
            "could not read {path:?}: {e}" => "не удалось прочитать {path:?}: {e}",
            "file {path:?} exceeds the {} MiB limit" => "файл {path:?} превышает лимит {} МБ",
            "could not open {path:?}: {err}" => "не удалось открыть {path:?}: {err}",
            "could not create the song list folder: {e}" => "не удалось создать папку списка песен: {e}",
            "could not locate the song list folder" => "не удалось определить папку списка песен",
            "known-song list is too large; the previous file was kept" => "список известных песен слишком большой; прежний файл не заменён",
            "could not save the song list: {e}" => "не удалось сохранить список песен: {e}",
            "{problem}; backup failed: {error}; the previous file was kept" => "{problem}; не удалось сохранить копию: {error}; прежний файл оставлен на месте",
            "{problem}; the old copy was saved alongside" => "{problem}; старая копия сохранена рядом",
            "{problem}; backup unavailable, the previous file was kept" => "{problem}; резервная копия недоступна, прежний файл оставлен на месте",
            "could not create the server song list folder: {e}" => "не удалось создать папку списка песен сервера: {e}",
            "could not locate the server song list folder" => "не удалось определить папку списка песен сервера",
            "server song list is too large; the previous file was kept" => "список песен сервера слишком большой; прежний файл не заменён",
            "could not save the server song list: {e}" => "не удалось сохранить список песен сервера: {e}",
            "unsupported server song list" => "неподдерживаемый список песен сервера",
            "server song list is damaged" => "список песен сервера повреждён",
            "server song list" => "список песен сервера",
            "unsupported known-song list; the file was kept unchanged" => "неподдерживаемый список известных песен; файл сохранён без изменений",
            "known-song list is damaged; the file was kept unchanged" => "список известных песен повреждён; файл сохранён без изменений",
            "known-song list" => "список известных песен",
            "could not read {what}: {e}" => "не удалось прочитать {what}: {e}",
            "{what} is too large; the file was kept unchanged" => "{what} слишком большой; файл сохранён без изменений",
            "could not read {what}: {err}" => "не удалось прочитать {what}: {err}",
            "library scan cancelled" => "проверка библиотеки отменена",
            "too many albums for a paginated scan" => "слишком много альбомов для постраничного обхода",
            "too many songs: full scan stopped without silently truncating the list" => "слишком много песен: полный обход прерван, список не обрезан молча",
            "library metadata exceeds 32 MiB; full scan stopped and the previous list was kept" => "метаданные библиотеки превышают 32 МБ; полный обход прерван, прежний список сохранён",
            "too many albums: full scan stopped without silently truncating the list" => "слишком много альбомов: полный обход прерван, список не обрезан молча",
            "album list changed during the scan or the server repeated a page; try again" => "список альбомов изменился во время обхода или сервер повторяет страницу; повторите проверку",
            "server returned more albums than requested in a page" => "сервер прислал больше альбомов, чем запрошено в одной странице",
            "internal error while scanning the library" => "внутренняя ошибка при проверке библиотеки",
            "could not finish the cache file: {e}" => "не удалось завершить файл кеша: {e}",
            "cache file path changed during the download" => "путь файла кеша изменился во время загрузки",
            "stream ended before the track was complete" => "поток оборвался до конца трека",
            "server returned an empty track" => "сервер прислал пустой трек",
            "could not save the cache: {e}" => "не удалось сохранить кеш: {e}",
            "could not write the cache: {e}" => "не удалось записать кеш: {e}",
            "stream exceeded the file size limit" => "поток превысил допустимый размер файла",
            "stream interrupted: {e}" => "поток оборвался: {e}",
            "could not create {}: {e}" => "не удалось создать {}: {e}",
            "could not create {parent:?}: {e}" => "не удалось создать {parent:?}: {e}",
            "server returned a file that is too large" => "сервер прислал слишком большой файл",
            "internal error while downloading the track" => "внутренняя ошибка при загрузке трека",
            "could not open {}: {e}" => "не удалось открыть {}: {e}",
            "server is streaming the track too slowly" => "сервер слишком медленно отдаёт трек",
            "decoder needs more data" => "декодеру нужно дождаться дополнительных данных",
            "playback stopped" => "воспроизведение остановлено",
            "index file is too large" => "файл индекса слишком большой",
            "cache index is damaged; backup failed, index saving is blocked" => "индекс кеша повреждён; копию сделать не удалось, сохранение индекса заблокировано",
            "cache index was damaged and reset; the old file was saved as {name}" => "индекс кеша повреждён и начат заново; старый файл сохранён как {name}",
            "skipped unsafe entries in the cache index: {dropped}" => "в индексе кеша пропущено записей с небезопасным путём: {dropped}",
            "could not create the cache: {e}" => "не удалось создать кеш: {e}",
            "cache index is too large" => "индекс кеша слишком большой",
            "cache index could not be read; saving is blocked to prevent data loss" => "индекс кеша не был прочитан; сохранение заблокировано во избежание потери данных",
            "could not delete files: {count}" => "не удалось удалить файлов: {count}",
            "could not delete the file: {err}" => "не удалось удалить файл: {err}",
            "file path contains a link or is outside the cache folder" => "путь файла содержит ссылку или выходит за пределы кеша",
            "track path is outside the cache folder" => "путь трека выходит за пределы папки кеша",
            "cache destination contains a link or an unsafe path" => "папка назначения кеша содержит ссылку или небезопасный путь",
            "track is already downloading" => "трек уже загружается",
            "track is already cached" => "трек уже находится в кеше",
            "unsafe track path in the cache index" => "путь трека в индексе кеша небезопасен",
            "could not migrate the previous cache index: {error}; audio files were kept" => "не удалось перенести прежний индекс кеша: {error}; аудиофайлы сохранены",
            "server: {message}" => "сервер: {message}",
            "server: {message} (code {code})" => "сервер: {message} (код {code})",
            "server rejected the request" => "сервер отклонил запрос",
            "response is not a Subsonic API response (missing subsonic-response)" => "ответ не похож на Subsonic API (нет subsonic-response)",
            "could not parse the server response" => "не удалось разобрать ответ сервера",
            "network: {root}" => "сеть: {root}",
            "network: server is not responding; check its URL and your connection" => "сеть: сервер не отвечает; проверьте адрес и соединение",
            "server response is too large" => "ответ сервера слишком большой",
            "could not read the server response: {e}" => "не удалось прочитать ответ сервера: {e}",
            "server URL must use HTTPS (HTTP is allowed only for localhost), without credentials, query or fragment" => "адрес сервера должен быть HTTPS (HTTP допустим только для localhost) и без логина, параметров или фрагмента",
            "server URL has no host" => "адрес сервера без хоста",
            "invalid server URL" => "некорректный адрес сервера",
            "server redirects to another origin; enter the final server URL in settings" => "сервер перенаправляет на другой адрес; укажите в настройках итоговый адрес сервера",
            "too many redirects" => "слишком много перенаправлений",
            "stream: HTTP {} — {}" => "поток: HTTP {} — {}",
            "cover: HTTP {} — {}" => "обложка: HTTP {} — {}",
            "server returned an incomplete album song list" => "сервер прислал неполный список песен альбома",
            "server returned an invalid song list" => "сервер прислал некорректный список песен",
            "server returned a different album for the library scan" => "сервер прислал другой альбом для проверки библиотеки",
            "server did not return an album for the library scan" => "сервер не прислал альбом для проверки библиотеки",
            "server returned an incomplete album page; full scan stopped" => "сервер прислал неполную страницу альбомов; полный обход прерван",
            "server returned an invalid album list" => "сервер прислал некорректный список альбомов",
            "server did not return an album list" => "сервер не прислал список альбомов",
            "server returned invalid UTF-8" => "сервер прислал некорректный UTF-8",
            "[salt hidden]" => "[salt скрыт]",
            "[token hidden]" => "[токен скрыт]",
            "[password hidden]" => "[пароль скрыт]",
            "invalid request URL" => "некорректный адрес запроса",
            "HTTP client: {e}" => "HTTP-клиент: {e}",
            _ => text,
        },
    }
}

macro_rules! trf {
    ("HTTP-клиент: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("HTTP-клиент: {e}" $($args)*)
            } else {
                format!("HTTP client: {e}" $($args)*)
            }
        }
    };
    ("обложка: HTTP {} — {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("обложка: HTTP {} — {}" $($args)*)
            } else {
                format!("cover: HTTP {} — {}" $($args)*)
            }
        }
    };
    ("поток: HTTP {} — {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("поток: HTTP {} — {}" $($args)*)
            } else {
                format!("stream: HTTP {} — {}" $($args)*)
            }
        }
    };
    ("не удалось прочитать ответ сервера: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось прочитать ответ сервера: {e}" $($args)*)
            } else {
                format!("could not read the server response: {e}" $($args)*)
            }
        }
    };
    ("сеть: {root}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("сеть: {root}" $($args)*)
            } else {
                format!("network: {root}" $($args)*)
            }
        }
    };
    ("сервер: {message} (код {code})" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("сервер: {message} (код {code})" $($args)*)
            } else {
                format!("server: {message} (code {code})" $($args)*)
            }
        }
    };
    ("сервер: {message}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("сервер: {message}" $($args)*)
            } else {
                format!("server: {message}" $($args)*)
            }
        }
    };
    ("не удалось перенести прежний индекс кеша: {error}; аудиофайлы сохранены" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось перенести прежний индекс кеша: {error}; аудиофайлы сохранены" $($args)*)
            } else {
                format!("could not migrate the previous cache index: {error}; audio files were kept" $($args)*)
            }
        }
    };
    ("не удалось удалить файл: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось удалить файл: {err}" $($args)*)
            } else {
                format!("could not delete the file: {err}" $($args)*)
            }
        }
    };
    ("не удалось удалить файлов: {count}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось удалить файлов: {count}" $($args)*)
            } else {
                format!("could not delete files: {count}" $($args)*)
            }
        }
    };
    ("не удалось создать кеш: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать кеш: {e}" $($args)*)
            } else {
                format!("could not create the cache: {e}" $($args)*)
            }
        }
    };
    ("в индексе кеша пропущено записей с небезопасным путём: {dropped}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("в индексе кеша пропущено записей с небезопасным путём: {dropped}" $($args)*)
            } else {
                format!("skipped unsafe entries in the cache index: {dropped}" $($args)*)
            }
        }
    };
    ("индекс кеша повреждён и начат заново; старый файл сохранён как {name}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("индекс кеша повреждён и начат заново; старый файл сохранён как {name}" $($args)*)
            } else {
                format!("cache index was damaged and reset; the old file was saved as {name}" $($args)*)
            }
        }
    };
    ("не удалось открыть {}: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось открыть {}: {e}" $($args)*)
            } else {
                format!("could not open {}: {e}" $($args)*)
            }
        }
    };
    ("не удалось создать {parent:?}: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать {parent:?}: {e}" $($args)*)
            } else {
                format!("could not create {parent:?}: {e}" $($args)*)
            }
        }
    };
    ("не удалось создать {}: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать {}: {e}" $($args)*)
            } else {
                format!("could not create {}: {e}" $($args)*)
            }
        }
    };
    ("поток оборвался: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("поток оборвался: {e}" $($args)*)
            } else {
                format!("stream interrupted: {e}" $($args)*)
            }
        }
    };
    ("не удалось записать кеш: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось записать кеш: {e}" $($args)*)
            } else {
                format!("could not write the cache: {e}" $($args)*)
            }
        }
    };
    ("не удалось сохранить кеш: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось сохранить кеш: {e}" $($args)*)
            } else {
                format!("could not save the cache: {e}" $($args)*)
            }
        }
    };
    ("не удалось завершить файл кеша: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось завершить файл кеша: {e}" $($args)*)
            } else {
                format!("could not finish the cache file: {e}" $($args)*)
            }
        }
    };
    ("не удалось прочитать {what}: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось прочитать {what}: {err}" $($args)*)
            } else {
                format!("could not read {what}: {err}" $($args)*)
            }
        }
    };
    ("{what} слишком большой; файл сохранён без изменений" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{what} слишком большой; файл сохранён без изменений" $($args)*)
            } else {
                format!("{what} is too large; the file was kept unchanged" $($args)*)
            }
        }
    };
    ("не удалось прочитать {what}: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось прочитать {what}: {e}" $($args)*)
            } else {
                format!("could not read {what}: {e}" $($args)*)
            }
        }
    };
    ("не удалось сохранить список песен сервера: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось сохранить список песен сервера: {e}" $($args)*)
            } else {
                format!("could not save the server song list: {e}" $($args)*)
            }
        }
    };
    ("не удалось создать папку списка песен сервера: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать папку списка песен сервера: {e}" $($args)*)
            } else {
                format!("could not create the server song list folder: {e}" $($args)*)
            }
        }
    };
    ("{problem}; резервная копия недоступна, прежний файл оставлен на месте" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{problem}; резервная копия недоступна, прежний файл оставлен на месте" $($args)*)
            } else {
                format!("{problem}; backup unavailable, the previous file was kept" $($args)*)
            }
        }
    };
    ("{problem}; старая копия сохранена рядом" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{problem}; старая копия сохранена рядом" $($args)*)
            } else {
                format!("{problem}; the old copy was saved alongside" $($args)*)
            }
        }
    };
    ("{problem}; не удалось сохранить копию: {error}; прежний файл оставлен на месте" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{problem}; не удалось сохранить копию: {error}; прежний файл оставлен на месте" $($args)*)
            } else {
                format!("{problem}; backup failed: {error}; the previous file was kept" $($args)*)
            }
        }
    };
    ("не удалось сохранить список песен: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось сохранить список песен: {e}" $($args)*)
            } else {
                format!("could not save the song list: {e}" $($args)*)
            }
        }
    };
    ("не удалось создать папку списка песен: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать папку списка песен: {e}" $($args)*)
            } else {
                format!("could not create the song list folder: {e}" $($args)*)
            }
        }
    };
    ("не удалось открыть {path:?}: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось открыть {path:?}: {err}" $($args)*)
            } else {
                format!("could not open {path:?}: {err}" $($args)*)
            }
        }
    };
    ("файл {path:?} превышает лимит {} МБ" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("файл {path:?} превышает лимит {} МБ" $($args)*)
            } else {
                format!("file {path:?} exceeds the {} MiB limit" $($args)*)
            }
        }
    };
    ("не удалось прочитать {path:?}: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось прочитать {path:?}: {e}" $($args)*)
            } else {
                format!("could not read {path:?}: {e}" $($args)*)
            }
        }
    };
    ("файл {path:?} не в UTF-8" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("файл {path:?} не в UTF-8" $($args)*)
            } else {
                format!("file {path:?} is not UTF-8" $($args)*)
            }
        }
    };
    ("не удалось записать {path:?}: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось записать {path:?}: {e}" $($args)*)
            } else {
                format!("could not write {path:?}: {e}" $($args)*)
            }
        }
    };
    ("защита пароля Windows: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("защита пароля Windows: {}" $($args)*)
            } else {
                format!("Windows password protection: {}" $($args)*)
            }
        }
    };
    ("config.json повреждён — загружены значения по умолчанию; старый файл сохранён как {name}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("config.json повреждён — загружены значения по умолчанию; старый файл сохранён как {name}" $($args)*)
            } else {
                format!("config.json is damaged — defaults were loaded; the old file was saved as {name}" $($args)*)
            }
        }
    };
    ("{err}; сохранение заблокировано" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{err}; сохранение заблокировано" $($args)*)
            } else {
                format!("{err}; saving is blocked" $($args)*)
            }
        }
    };
    ("не удалось защитить сохранённый пароль: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось защитить сохранённый пароль: {err}" $($args)*)
            } else {
                format!("could not protect the saved password: {err}" $($args)*)
            }
        }
    };
    ("не удалось создать {dir:?}: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать {dir:?}: {e}" $($args)*)
            } else {
                format!("could not create {dir:?}: {e}" $($args)*)
            }
        }
    };
    ("пароль не сохранён: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("пароль не сохранён: {err}" $($args)*)
            } else {
                format!("password was not saved: {err}" $($args)*)
            }
        }
    };
    ("не удалось защитить пароль; настройки не изменены: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось защитить пароль; настройки не изменены: {err}" $($args)*)
            } else {
                format!("could not protect the password; settings were kept unchanged: {err}" $($args)*)
            }
        }
    };
    ("не удалось создать {}: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать {}: {err}" $($args)*)
            } else {
                format!("could not create {}: {err}" $($args)*)
            }
        }
    };
    ("библиотека обновлена: {count} треков с сервера" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("библиотека обновлена: {count} треков с сервера" $($args)*)
            } else {
                format!("library refreshed: {count} songs from the server" $($args)*)
            }
        }
    };
    ("не удалось обновить библиотеку после {albums} альбомов: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось обновить библиотеку после {albums} альбомов: {err}" $($args)*)
            } else {
                format!("could not refresh the library after {albums} albums: {err}" $($args)*)
            }
        }
    };
    ("запомнено альбомов: {}; новые песни будут скачиваться автоматически" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("запомнено альбомов: {}; новые песни будут скачиваться автоматически" $($args)*)
            } else {
                format!("remembered albums: {}; new songs will be cached automatically" $($args)*)
            }
        }
    };
    ("проверено альбомов: {}; добавлено в загрузки: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("проверено альбомов: {}; добавлено в загрузки: {}" $($args)*)
            } else {
                format!("albums checked: {}; downloads added: {}" $($args)*)
            }
        }
    };
    ("проверка библиотеки остановлена после {} альбомов (добавлено: {}): {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("проверка библиотеки остановлена после {} альбомов (добавлено: {}): {err}" $($args)*)
            } else {
                format!("library scan stopped after {} albums (added: {}): {err}" $($args)*)
            }
        }
    };
    ("скачано: {} — {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("скачано: {} — {}" $($args)*)
            } else {
                format!("downloaded: {} — {}" $($args)*)
            }
        }
    };
    ("не скачалось: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не скачалось: {err}" $($args)*)
            } else {
                format!("download failed: {err}" $($args)*)
            }
        }
    };
    ("файл уже лежит в папке кеша: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("файл уже лежит в папке кеша: {}" $($args)*)
            } else {
                format!("file is already in the cache folder: {}" $($args)*)
            }
        }
    };
    ("уже в кеше: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("уже в кеше: {}" $($args)*)
            } else {
                format!("already cached: {}" $($args)*)
            }
        }
    };
    ("в загрузки добавлено треков: {added}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("в загрузки добавлено треков: {added}" $($args)*)
            } else {
                format!("tracks added to downloads: {added}" $($args)*)
            }
        }
    };
    ("КЕШ {cached} · {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("КЕШ {cached} · {}" $($args)*)
            } else {
                format!("CACHE {cached} · {}" $($args)*)
            }
        }
    };
    ("{label}: {} альбомов" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{label}: {} альбомов" $($args)*)
            } else {
                format!("{label}: {} albums" $($args)*)
            }
        }
    };
    ("новых загрузок: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("новых загрузок: {}" $($args)*)
            } else {
                format!("new downloads: {}" $($args)*)
            }
        }
    };
    ("треков в очереди: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("треков в очереди: {}" $($args)*)
            } else {
                format!("queue: {} tracks" $($args)*)
            }
        }
    };
    ("кеш: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("кеш: {}" $($args)*)
            } else {
                format!("cache: {}" $($args)*)
            }
        }
    };
    ("конфиг не сохранён: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("конфиг не сохранён: {err}" $($args)*)
            } else {
                format!("config was not saved: {err}" $($args)*)
            }
        }
    };
    ("альбомов: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("альбомов: {}" $($args)*)
            } else {
                format!("albums: {}" $($args)*)
            }
        }
    };
    ("треков: {}, {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("треков: {}, {}" $($args)*)
            } else {
                format!("tracks: {}, {}" $($args)*)
            }
        }
    };
    ("всего {total} · на диске {disk}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("всего {total} · на диске {disk}" $($args)*)
            } else {
                format!("total {total} · on disk {disk}" $($args)*)
            }
        }
    };
    ("загружаю с сервера: {} альбомов" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("загружаю с сервера: {} альбомов" $($args)*)
            } else {
                format!("loading from server: {} albums" $($args)*)
            }
        }
    };
    ("найдено {found} из {total}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("найдено {found} из {total}" $($args)*)
            } else {
                format!("found {found} of {total}" $($args)*)
            }
        }
    };
    ("{} треков по истории BEAT" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{} треков по истории BEAT" $($args)*)
            } else {
                format!("{} tracks from your BEAT history" $($args)*)
            }
        }
    };
    ("по умолчанию: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("по умолчанию: {}" $($args)*)
            } else {
                format!("default: {}" $($args)*)
            }
        }
    };
    ("{kb:.0} КБ" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{kb:.0} КБ" $($args)*)
            } else {
                format!("{kb:.0} KiB" $($args)*)
            }
        }
    };
    ("{:.1} МБ" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{:.1} МБ" $($args)*)
            } else {
                format!("{:.1} MiB" $($args)*)
            }
        }
    };
    ("{:.2} ГБ" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{:.2} ГБ" $($args)*)
            } else {
                format!("{:.2} GiB" $($args)*)
            }
        }
    };
    ("не удалось создать мьютекс: {}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать мьютекс: {}" $($args)*)
            } else {
                format!("could not create the mutex: {}" $($args)*)
            }
        }
    };
    ("{err}.\n\nЗакройте уже открытое окно BEAT и запустите это снова." $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("{err}.\n\nЗакройте уже открытое окно BEAT и запустите это снова." $($args)*)
            } else {
                format!("{err}.\n\nClose the other BEAT window and launch this one again." $($args)*)
            }
        }
    };
    ("BEAT не смог продолжить работу.\n\n{info}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("BEAT не смог продолжить работу.\n\n{info}" $($args)*)
            } else {
                format!("BEAT could not continue.\n\n{info}" $($args)*)
            }
        }
    };
    ("аудиовыход недоступен: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("аудиовыход недоступен: {e}" $($args)*)
            } else {
                format!("audio output unavailable: {e}" $($args)*)
            }
        }
    };
    ("перемотка недоступна: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("перемотка недоступна: {e}" $($args)*)
            } else {
                format!("seeking unavailable: {e}" $($args)*)
            }
        }
    };
    ("beat: аудиопоток: {err}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("beat: аудиопоток: {err}" $($args)*)
            } else {
                format!("beat: audio stream: {err}" $($args)*)
            }
        }
    };
    ("не удалось прочитать {}: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось прочитать {}: {e}" $($args)*)
            } else {
                format!("could not read {}: {e}" $($args)*)
            }
        }
    };
    ("метаданные: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("метаданные: {e}" $($args)*)
            } else {
                format!("metadata: {e}" $($args)*)
            }
        }
    };
    ("декодер: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("декодер: {e}" $($args)*)
            } else {
                format!("decoder: {e}" $($args)*)
            }
        }
    };
    ("не удалось прочитать сессию: {detail}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось прочитать сессию: {detail}" $($args)*)
            } else {
                format!("could not read the session: {detail}" $($args)*)
            }
        }
    };
    ("не удалось сохранить сессию: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось сохранить сессию: {e}" $($args)*)
            } else {
                format!("could not save the session: {e}" $($args)*)
            }
        }
    };
    ("не удалось создать папку сессии: {e}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("не удалось создать папку сессии: {e}" $($args)*)
            } else {
                format!("could not create the session folder: {e}" $($args)*)
            }
        }
    };
    ("Windows media controls: {error}" $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("Windows media controls: {error}" $($args)*)
            } else {
                format!("Windows media controls: {error}" $($args)*)
            }
        }
    };
    ("Причина: {e}\n\nДля запуска нужен OpenGL 2.1+. Включите 3D-ускорение в настройках ВМ либо запустите программу на обычном рабочем столе." $($args:tt)*) => {
        {
            if $crate::i18n::current() == $crate::i18n::Language::Ru {
                format!("Причина: {e}\n\nДля запуска нужен OpenGL 2.1+. Включите 3D-ускорение в настройках ВМ либо запустите программу на обычном рабочем столе." $($args)*)
            } else {
                format!("Reason: {e}\n\nOpenGL 2.1+ is required. Enable 3D acceleration in the VM settings or run BEAT on a normal desktop." $($args)*)
            }
        }
    };
}
pub(crate) use trf;
